version: '3.4'

services:
  nats:
    image: nats:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nats.rule=Host(`apistaging.secureapi.dev`)"
      - "traefik.http.routers.nats.entrypoints=nats"
    ports:
      - "4222:4222"
    command: "-DV"

  django:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`apistaging.secureapi.dev`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=myresolver"
    image: secureapi/web:8de4db25ada25743dcff804a83d816606119df85
    env_file:
      - .template.env
    ports:
      - "8072:8000"
    command: /start

  test_saver:
    image: secureapi/test_saver:f36b84b0521dac19af9674cd0984b717d01378ae
    env_file:
      - .template.env
    depends_on:
      - nats

  boatswain:
    image: secureapi/boatswain:bcb5a991a1cdbeb2799782fbc7452f64b03d20a6
    env_file:
      - .template.env
    depends_on:
      - nats

  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.nats.address=:4222"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=pbojanowski@protonmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
