version: '3.4'

services:
  nats:
    image: nats:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nats.rule=Host(`apistaging.secureapi.dev`)"
      - "traefik.http.routers.nats.entrypoints=nats"
    ports:
      - "4222:4222"
    command: "-DV"

  django:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`apistaging.secureapi.dev`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=myresolver"
    image: secureapi/web:92062849af2b940f1694c9c8f65980a2558a4c3c
    env_file:
      - .template.env
    ports:
      - "8072:8000"
    command: /start

  test_saver:
    image: secureapi/test_saver:537d42fcb1c9e09e27e369d1f3b2a505702f8682
    env_file:
      - .template.env
    depends_on:
      - nats

  boatswain:
    image: secureapi/boatswain:96f525ad639db56ecce725ec1de4baeb5bf903a4
    env_file:
      - .template.env
    depends_on:
      - nats

  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.nats.address=:4222"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=pbojanowski@protonmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
