 version: 2

 jobs:
   deploy-staging:
     machine:
       enabled: true
     steps:
       - add_ssh_keys:
           fingerprints:
             - "b9:a8:15:64:bb:2b:e4:24:42:da:a7:e7:3f:9e:99:e2"
#       - run:
#           name: Pull docker images
#           command: |
#             ssh $SSH_USER@$SSH_HOST sudo docker-compose -f /home/ubuntu/app/secureapi-dev/docker-compose-prod.yml pull
       - run:
           name: Start docker compose
           command: |
             ssh -vvv $SSH_USER@$SSH_HOST ./home/ubuntu/app/secureapi-dev/start.sh
          # && sudo docker-compose -f docker-compose-prod.yml up --force-recreate -d


 workflows:
   version: 2
   deploy-staging:
     jobs:
       - deploy-staging:
           filters:
             branches:
               only: staging
   deploy-prod:
     jobs:
       - deploy:
           filters:
             branches:
               only: prod
